name: CI/CD Workflow for sonasid-disup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PROJECT_DIR: .       # Change if your project lives in a subdirectory
  APP_NAME: sonasid-disup

jobs:
  Build_And_Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Build application
        run: npm run build --if-present
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ${{ env.PROJECT_DIR }}/dist

  Deploy_On_Development:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [Build_And_Test]
    environment:
      name: Production
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ${{ env.PROJECT_DIR }}/dist

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_55EA0D267664432DB6C85FC6FD7D0239 }}
          package: ${{ env.PROJECT_DIR }}/dist
